#!/bin/bash
#run with "sudo -u alison ~alison/bin/install_Ubuntu_IVI_Qemu"
#Without -u, xauth error:
#"Could not initialize SDL(No available video device) - exiting"
ROOTDIR=/fedora14/bonnet_f14/opt/opt/Ubuntu
sudo qemu-img create -f raw ${ROOTDIR}/ubuntu_ivi_natty.raw 10G
sudo chown alison ${ROOTDIR}/ubuntu_ivi_natty.raw 
#installs from "cdrom" onto "hard disk a"
qemu-system-i386 --enable-kvm --cdrom ${ROOTDIR}/falmouth-natty-x86-iso-20111219-2.iso -boot d -hda ${ROOTDIR}/ubuntu_ivi_natty.raw -m 4096 -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -name ubuntu_ivi_natty -localtime -no-reboot
