#!/bin/bash
#qemu-kvm -boot c -hda /opt/ubuntu_11.10.raw -m 4096 -usb -soundhw all -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_11.10 -localtime
#looks like Ubuntu uses 6666 for IRC?
#qemu-kvm -boot c -hda /opt/ubuntu_ivi_natty.raw -m 2048 -usb -soundhw all -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_ivi -localtime
qemu-system-i386 --enable-kvm -boot c -hda /fedora14/ubuntu_ivi_natty.raw -m 4096 -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -name ubuntu_ivi_natty -localtime
