#!/bin/bash
ROOTDIR=/fedora14/bonnet_f14/opt/opt/Ubuntu
#qemu-kvm -boot c -hda /opt/ubuntu_11.10.raw -m 4096 -usb -soundhw all -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_11.10 -localtime
#looks like Ubuntu uses 6666 for IRC?
#qemu-system-i386 -boot c -hda /fedora14/ubuntu_nobdy_bldr.raw -m 4096 -usb -soundhw all -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_nobdy_bldr -localtime
#qemu-system-i386 -boot c -hda /fedora14/ubuntu_nobdy_bldr.raw -m 4096 -usb -soundhw all -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_nobdy_bldr -localtime
#comes up without GUI
#qemu -boot c -hda /fedora14/ubuntu_nobdy_bldr.raw -m 2048 -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga std -name ubuntu_nobdy_bldr -localtime
#extremely slow, but does work
#qemu -boot c -hda /fedora14/ubuntu_nobdy_bldr.raw -m 2048 -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -vga cirrus -name ubuntu_nobdy_bldr -localtime
qemu-system-i386 --enable-kvm -boot c -hda ${ROOTDIR}/ubuntu_debian.raw -m 4096 -net nic,model=e1000  -net user,hostfwd=tcp:127.0.0.1:6666-:22 -name ubuntu_debian -localtime
