#!/bin/bash
###############################################################################
##                                                                           ##
##      File:     wsrcc-configure-f10                                        ##
##      Author:   Wolfgang S. Rupprecht <wolfgang@wsrcc.com>                 ##
##      Created:  Tue Nov 25 10:14:58 PST 2008                               ##
##      Contents: configure a raw f10 system to run at wsrcc                 ##
##                                                                           ##
##      Copyright (c) 2008 Wolfgang S. Rupprecht.                            ##
##      All rights reserved.                                                 ##
##                                                                           ##
##      $Id$
###############################################################################

export BACKUP=/f8  # for bonnet
inst ()
{
   if [ -f $1 ]
   then
       if [ ! -f ${1}-dist ]
       then
           # echo "Saving OLD $1 file to *-dist"
           mv $1 ${1}-dist
       else
           echo "OLD $1 dist file already saved to *-dist"
       fi
       cp -cdp $BACKUP/$1 $1
       chcon --reference=${1}-dist $1
   else
       echo "Installign NEW $1 file.  No dist file found."
       cp -cdp $BACKUP/$1 $1
   fi
}

# same thing, but different printf's.  Only print out stuff if
# something unexpected happens.
# usage; inst absolutefilename
inst-new ()
{
   if [ -f $1 ]
   then
       if [ ! -f ${1}-dist ]
       then
           echo "Saving OLD $1 file to *-dist"
           mv $1 ${1}-dist
       else
           echo "OLD $1 dist file already saved to *-dist"
       fi
       cp -cdp $BACKUP/$1 $1
       chcon --reference=${1}-dist $1
   else
       # echo "Installign NEW $1 file.  No dist file found."
       cp -cdp $BACKUP/$1 $1
   fi
}

save ()
{
   if [ ! -f ${1}-dist ]
   then
       cp -cdp $1 ${1}-dist
   else
       echo "OLD $1 dist file already saved to *-dist"
   fi
}
